/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef thriftDemo_CONSTANTS_H
#define thriftDemo_CONSTANTS_H

#include "thriftDemo_types.h"

namespace thriftDemo {

class thriftDemoConstants {
 public:
  thriftDemoConstants();

};

extern const thriftDemoConstants g_thriftDemo_constants;

} // namespace

#endif
