/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "thriftDemo_constants.h"

namespace thriftDemo {

const thriftDemoConstants g_thriftDemo_constants;

thriftDemoConstants::thriftDemoConstants() {
}

} // namespace

